name: Example
on:
  workflow_dispatch:
    inputs:
      project-owner:
        required: true
        description: 'User/Organization name project contains.'
      project-number:
        default: 0
        required: true
        description: 'The number of the target project.'

jobs:
  example:
    name: Example job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Project Id
      id: get-project-id
      uses: ./
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        project-owner: ${{ github.event.inputs.project-owner }}
        project-number: ${{ github.event.inputs.project-number }}
    - name: Output result
      run: |
        echo '${{ steps.get-project-id.outputs.project-id }}'
