name: Tests
on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
jobs:
  test-project-found:
    name: Project found
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Project Id
      id: get-project-id
      uses: ./
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        project-owner: 'monry'
        project-number: 3
    - name: Assert
      run: |
        test '${{ steps.get-project-id.outputs.project-id }}' = 'PVT_kwHOAAzNIc4AFSrF'
  test-project-not-found:
    name: Project not found
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Project Id
      id: get-project-id
      uses: ./
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        project-owner: 'monry'
        project-number: -1
    - name: Assert
      run: |
        test '${{ steps.get-project-id.outputs.error }}' = 'Project does not found.'
